name: Maintenance checks
on:
    pull_request:
        paths:
            - '.github/workflows/**'
            - 'server/**'
            - 'client/**'
            - 'common/**'
            - 'tester/**'
            - 'build.gradle.kts'
jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: >-
                   sudo apt update                                                   &&
                   sudo apt install wget                                             &&
                   wget https://apt.llvm.org/llvm.sh                                 &&
                   chmod a+x llvm.sh                                                 &&
                   sudo ./llvm.sh 17                                                 &&
                   (sudo rm /usr/bin/clang-format || exit 0)                         &&
                   sudo apt -y install clang-format-17                               &&
                   sudo ln -sf "$(command -v clang-format-17)" /usr/bin/clang-format
            - run: ./format.sh --check

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'

            - run: ./gradlew --no-daemon build
