name: Maintenance checks
on:
    pull_request:
        paths:
            - '.github/workflows/**'
            - 'server/**'
            - 'client/**'
            - 'common/**'
            - 'tester/**'
            - 'build.gradle.kts'
jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            # clang-format doesn't come with act's local images.
            - run: >-
                   if [ -n "$ACT" ]; then
                       apt update                                             &&
                       apt install wget                                       &&
                       wget https://apt.llvm.org/llvm.sh                      &&
                       chmod +x llvm.sh                                       &&
                       ./llvm.sh 17                                           &&
                       apt -y install clang-format-17                         &&
                       ln -s "$(which clang-format-17)" /usr/bin/clang-format
                   fi
            - run: clang-format-17 --version
            - run: ./format.sh --check

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'

            - run: ./gradlew --no-daemon build
